id: IAA92D5AD
legacy_id: P008005
ocr_import_info:
  bdrc_scan_id: W30405
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T17:01:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:36:29.412708+00:00'
last_modified: 2022-09-03 19:36:33.983897
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30405
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW30405
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དྲི་བསུང་པདྨའི་འདབ་སྟོང་གི་རྟགས་ཀྱི་འཇུག་འགྲེལ།
  author: སློབ་དཔོན་ཐེག་མཆོག
statistics:
  ocr_word_mean_confidence_index: 0.9524579195663182
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I6099:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6099
      total_pages: 226
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6099.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9524579195663182
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
