id: IAA92D5AD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T17:01:43+00:00'
last_modified: '2022-06-16T05:44:55.611765+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30405
  title: དྲི་བསུང་པདྨའི་འདབ་སྟོང་གི་རྟགས་ཀྱི་འཇུག་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    D6FD:
      image_group_id: I6099
      title: ''
      total_pages: 226
      order: 1
      base_file: D6FD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
