id: P008005
initial_creation_type: ocr
source_metadata:
  id: bdr:W30405
  title: དྲི་བསུང་པདྨའི་འདབ་སྟོང་གི་རྟགས་ཀྱི་འཇུག་འགྲེལ
  author: ''
  volumes:
    d3c8ba1928b44133ad2418d6bcdb6823:
      image_group_id: I6099
      title: ''
      volume_number: 1
      total_pages: 226
      base_file: v001.txt
ebook_metadata:
  title: དྲི་བསུང་པདྨའི་འདབ་སྟོང་གི་རྟགས་ཀྱི་འཇུག་འགྲེལ
  author: ''
  sku: P008005
  cover: cover.jpg
  layers:
  - pagination
