id: P008005
initial_creation_type: ocr
source_metadata:
  id: bdr:W30405
  title: དྲི་བསུང་པདྨའི་འདབ་སྟོང་གི་རྟགས་ཀྱི་འཇུག་འགྲེལ
  author: ''
  volumes:
    d5d9dd6b3d494798b66766f837daf6e9:
      image_group_id: I6099
      title: ''
      volume_number: 1
      total_pages: 226
ebook_metadata:
  title: དྲི་བསུང་པདྨའི་འདབ་སྟོང་གི་རྟགས་ཀྱི་འཇུག་འགྲེལ
  author: ''
  sku: P008005
  cover: cover.jpg
  layers:
  - pagination
